version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - xtuc
  ignore:
  - dependency-name: wabt
    versions:
    - "> 1.0.0-nightly.20180421"
  - dependency-name: "@babel/types"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.13
    - 7.13.14
    - 7.13.17
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
  - dependency-name: "@babel/preset-flow"
    versions:
    - 7.12.13
