install:
  - cmd: git submodule -q update --init
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:NODEJS_VERSION
  - choco install make
  - yarn global add lerna@2
  - make LERNA=lerna bootstrap

test_script:
  - node --version
  - yarn --version
  - make TEST_TIMEOUT=6000 test-ci-windows

environment:
  NODEJS_VERSION: "10"
  DISABLE_FUZZER_TEST: 1

build: off
